# Generated by Django 3.0.6 on 2020-05-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseID',
            field=models.CharField(max_length=10),
        ),
    ]
